export enum APIType {
  TAX_AUTHORITY = 'TAX_AUTHORITY',
  JUDICIAL_SYSTEM = 'JUDICIAL_SYSTEM',
  BANKING_SYSTEM = 'BANKING_SYSTEM',
  BLOCKCHAIN_NETWORK = 'BLOCKCHAIN_NETWORK',
  COMPLIANCE_PLATFORM = 'COMPLIANCE_PLATFORM',
  IDENTITY_VERIFICATION = 'IDENTITY_VERIFICATION',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  CREDIT_BUREAU = 'CREDIT_BUREAU',
  FINANCIAL_ANALYSIS = 'FINANCIAL_ANALYSIS',
  AUDIT_SYSTEM = 'AUDIT_SYSTEM',
  REGULATORY_COMPLIANCE = 'REGULATORY_COMPLIANCE',
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
}

export enum IntegrationStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
  SYNCING = 'SYNCING',
}
